### PR TITLE
Add the phone number to the users index view

### PR DESCRIPTION
**Pull request by trevrobwhite**

### CODE REVIEW

**Comment by trevrobwhite** [comment]
@nook24 If you are able to approve this pull request that would be great, it's to add the phone number to the users view, so we can find which user is getting SMS alerts.

**Comment by nook24** [comment]
Hi @trevrobwhite, yes of course looks good for me.
One question, are you sure you want to add this to users? Because alerts are only send to contacts :)

**Comment by trevrobwhite** [comment]
@nook24 Yes, users book themselves into the On Call system add-on we developed which is outside the contacts because this dynamically changes based on the day/week whereas nagios is static

**Comment by trevrobwhite** [comment]
Thanks

**Comment by nook24** [comment]
You are welcome

**Pull request merged**
