### PR TITLE
Added translation for chinese

### PR DESCRIPTION
**Pull request by souravpd**

### CODE REVIEW

**Comment by nook24** [comment]
Many thanks @souravpd for your hard work! 🙂🎃
Did you cloned the ORM branch?

**Comment by souravpd** [comment]
Yes

**Comment by nook24** [comment]
Unfortunately you used the `development` branch which is quite old...
How ever, we will see how much of your translations we could re-use. Thanks a lot! :)

**Comment by souravpd** [comment]
Very grateful
Thankyou !

**Comment by binsky08** [comment]
Hi @souravpd thank you for your work with the chinese and korean translation.

> Unfortunately you used the development branch which is quite old...

The source file you translated from is between 2 and 4 years old and you regrettably cloned from the wrong branch (development instead of ORM, see tutorial in https://github.com/it-novum/openITCOCKPIT/issues/957).

Therefore we can't use your translation.

**Pull request closed without merging**
